# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [39]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [40]:
A = np.arange(1, 16).reshape(3,5)

In [36]:
A.ndim

2

In [41]:
A.shape

(3, 5)

In [42]:
A.size

15

In [45]:
A.dtype

dtype('int32')

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [21]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [48]:
B - C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [49]:
B * C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [50]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [22]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [51]:
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [55]:
B.min()

1

In [56]:
B.min(axis=1)

array([1, 4, 7])

In [57]:
B.min(axis=0)

array([1, 2, 3])

In [58]:
B.argmin()

0

In [60]:
B.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [61]:
B.sum()

45

In [62]:
np.mean(B, axis=0)

array([4., 5., 6.])

In [64]:
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [23]:
print(A)

[[1 2]
 [3 4]]


In [24]:
A[1]

array([3, 4])

**Answer:**

In [ ]:
# Betyder det att vi får alla värden från de axlar som vi inte angav ett index för. 
# Eftersom vi inte angav något index för den andra axeln (kolumner), kommer hela raden att returneras
# Det är andra rader eftersom vi tar index [1]

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [71]:
A 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [26]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [68]:
for elemnet in np.nditer(A):
    print(elemnet)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [72]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# med a = np.arange(30) extaheras en 1D array som inhåller alla talen mellan 0 - 29
# b = a.reshape((2, 3, -1)): reshape ändrar a från 1D array till 3D array, 
# b har tre parameter dvs tre axlar enligt följande: 
# 2 bevisar antal block (axel 1), 
# 3 bevisar antal rader i varje block (axel 2), 
# -1 betyder att tredje axel beräknas automatiskt baserat på de andra axlerna. 
# Vi har 30 element, 2 block och 3 rader vilket gör att vrdet av tredje axel är 5 (2*3*5=30), 
# 5 element i varje rad.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [73]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [74]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [30]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [ ]:
def add_mult_matrices(mat1, mat2, operation):
    if not isinstance(mat1, np.ndarray) or not isinstance(mat2, np.ndarray):
        raise TypeError("Both inputs must be of type numpy.ndarray")
    
    if operation not in ["add", "multiply"]:
        raise ValueError("The operation must be either 'add' or 'multiply'")
    
    if operation == 'add':
        if mat1.shape != mat2.shape:
            raise ValueError("Matrices must have the same size for addition")
        return mat1 + mat2
    elif operation == 'multiply':
        if mat1.shape(1) != mat2.shape(0):
            raise ValueError("The number of columns in the first matrix must equal the number of rows in the second matrix for multiplication")
        return mat1 @ mat2

    


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [104]:
# Uppgift 10.1.1.
x = np.array([4, 3])
x

array([4, 3])

In [90]:
# a
x.shape

(2,)

In [79]:
# b.
5 * x

array([20, 15])

In [81]:
# c.
3 * x

array([12,  9])

In [86]:
# d.
5 * x + 3 * x

array([32, 24])

In [83]:
# e.
8 * x

array([32, 24])

In [85]:
# f.
4 * x - x

array([12,  9])

In [87]:
# g.
x.T

array([4, 3])

In [88]:
x.T.shape

(2,)

In [91]:
# h.
x + x.T

array([8, 6])

In [96]:
#i.
np.linalg.norm(x)

5.0

In [103]:
# Uppgift 10.1.2
v = np.array([[3], [7], [0], [11]])
v

array([[ 3],
       [ 7],
       [ 0],
       [11]])

In [106]:
# a.
v.shape

(4, 1)

In [105]:
# b.
2 * v

array([[ 6],
       [14],
       [ 0],
       [22]])

In [107]:
# c.
5 * v + 2 * v


array([[21],
       [49],
       [ 0],
       [77]])

In [108]:
# d.
4 * v - 2 * v

array([[ 6],
       [14],
       [ 0],
       [22]])

In [109]:
# e.
v.T

array([[ 3,  7,  0, 11]])

In [110]:
v.T.shape

(1, 4)

In [111]:
# f.
np.linalg.norm(v)

13.379088160259652

In [118]:
# Uppgift 10.1.3.
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

print ("v1 =", v1)
print("v2 =", v2)

v1 = [4 3 1 5]
v2 = [2 3 1 1]


In [119]:
# a.
np.linalg.norm(v1)

7.14142842854285

In [120]:
# b.
np.linalg.norm(v1 - v2)

4.47213595499958

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [147]:
# Uppgift 10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])
print("Matris A:\n", A)
print("Matris B:\n", B)
print("Matris C:\n", C)
print("Matris D:\n", D)
print("Matris E:\n", E)
print("Matris I:\n", I)
            

Matris A:
 [[ 2  1 -1]
 [ 1 -1  1]]
Matris B:
 [[ 4 -2  1]
 [ 2 -4 -2]]
Matris C:
 [[1 2]
 [2 1]]
Matris D:
 [[3 4]
 [4 3]]
Matris E:
 [[1]
 [2]]
Matris I:
 [[1 0]
 [0 1]]


In [124]:
# a.
2 * A

array([[ 4,  2, -2],
       [ 2, -2,  2]])

In [125]:
# b.
B - 2 * A

array([[ 0, -4,  3],
       [ 0, -2, -4]])

In [126]:
# c. 
3 * C -2 * E

array([[ 1,  4],
       [ 2, -1]])

In [127]:
# d.
2 * D - 3 * D

array([[-3, -4],
       [-4, -3]])

In [128]:
# e.
D.T + 2 * D

array([[ 9, 12],
       [12,  9]])

In [129]:
# f.
2 * C.T - 2 * D.T

array([[-4, -4],
       [-4, -4]])

In [144]:
# g.
A.T - B # Ej definierat 

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [150]:
# h.
np.dot(A, C)

array([[ 4,  7],
       [ 8, 14]])

In [141]:
# i.
C @ D


array([[11, 10],
       [10, 11]])

In [140]:
# j.
C @ B

array([[  8, -10,  -3],
       [ 10,  -8,   0]])

In [139]:
# k.
C @ I

array([[1, 2],
       [2, 1]])

In [138]:
# l.
A @ B.T

array([[5, 2],
       [7, 4]])

In [148]:
#Uppgift 10.2.2.
A = np.array([[2, 3, 4], [5, 4, 1]])
print("Matris A:\n", A)

Matris A:
 [[2 3 4]
 [5 4 1]]


In [146]:
A @ A.T

array([[29, 26],
       [26, 42]])

In [149]:
# Uppgift 10.2.3.
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print("Matris A:\n", A)
print("Matris B:\n", B)
print("Matris C:\n", C)


Matris A:
 [[1 2]
 [2 4]]
Matris B:
 [[2 1]
 [1 3]]
Matris C:
 [[4 3]
 [0 2]]


In [154]:
A @ B == A @ C

array([[ True,  True],
       [ True,  True]])

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [31]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [32]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [33]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [ ]:
# Vi kontrollerar om v1 och v2 är view eller copy inom att använda .base-attributet
# Om .base retunerar None är arrayen en copy men om .base retunerar den ursprunliga arrayen är det en view

# När vi ändrar sista elementet i v2 till 123 ändras även sista elementet i v1 till 123
# Eftersom v2 är en view av v1 på grund av "basic indexing" retunerar en view.
# Det betyder att v2 och v1 delar samma underliggande data så varje ändring i v2 påverkar direkt v1.